export const productData = [
  {
    id: 1,
    name: "Leather Bag",
    description: "Stylish and durable leather bag for daily use.",
    price: 49.99,
    discountPrice: 39.99,
    image: "/images/product/product1.png",
    category: "Bag",
    manufacturer: "Massimo Palomba",
    ratings: 4.6,
    stock: 40,
    expire: "31-12-2026",
  },
  {
    id: 2,
    name: "Protein Bottle",
    description: "High-quality protein supplement for muscle recovery.",
    price: 12.99,
    discountPrice: 10.99,
    image: "/images/product/product2.png",
    category: "Bottle",
    manufacturer: "Dabur",
    ratings: 4.4,
    stock: 35,
    expire: "31-12-2026",
  },
  {
    id: 3,
    name: "Gym Cycle",
    description: "Sturdy and adjustable gym cycle for cardio workouts.",
    price: 199.99,
    discountPrice: 179.99,
    image: "/images/product/product3.png",
    category: "Cycle",
    manufacturer: "Patanjali",
    ratings: 4.5,
    stock: 10,
    expire: "31-12-2028",
  },
  {
    id: 4,
    name: "Leather Bag",
    description: "Premium quality leather bag with multiple compartments.",
    price: 79.99,
    discountPrice: 69.99,
    image: "/images/product/product4.png",
    category: "Bag",
    manufacturer: "Zandu",
    ratings: 4.3,
    stock: 45,
    expire: "31-12-2027",
  },
  {
    id: 5,
    name: "Gym Back Weight",
    description: "Adjustable gym back weight for strength training.",
    price: 18.99,
    discountPrice: 16.49,
    image: "/images/product/product5.png",
    category: "Gym Equipment",
    manufacturer: "Himalaya",
    ratings: 4.7,
    stock: 30,
    expire: "31-12-2025",
  },
  {
    id: 6,
    name: "Gym Ball",
    description: "Durable and anti-burst gym ball for fitness exercises.",
    price: 10.99,
    discountPrice: 9.49,
    image: "/images/product/product6.png",
    category: "Fitness Equipment",
    manufacturer: "Baidyanath",
    ratings: 4.2,
    stock: 55,
    expire: "31-12-2026",
  },
  {
    id: 7,
    name: "Hand Dumbbell",
    description: "Ergonomic hand dumbbell set for weight training.",
    price: 14.99,
    discountPrice: 12.99,
    image: "/images/product/product7.png",
    category: "Dumbbell",
    manufacturer: "Sri Sri Tattva",
    ratings: 4.6,
    stock: 38,
    expire: "31-12-2025",
  },
  {
    id: 8,
    name: "Gym Mat",
    description: "High-quality gym mat with non-slip surface.",
    price: 11.99,
    discountPrice: 10.49,
    image: "/images/product/product8.png",
    category: "Mat",
    manufacturer: "Hamdard",
    ratings: 3.4,
    stock: 0,
    expire: "31-12-2027",
  },
  {
    id: 9,
    name: "Gym Rope",
    description: "Heavy-duty gym rope for endurance training.",
    price: 19.99,
    discountPrice: 17.49,
    image: "/images/product/product9.png",
    category: "Rope",
    manufacturer: "Himalaya",
    ratings: 3.8,
    stock: 28,
    expire: "31-12-2025",
  },
];
